// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface Header {
}

export interface Request {
    body?: string;
    certificates?: string[];
    expectedStatusCode?: number;
    header?: outputs.Header;
    insecureSkipVerify?: boolean;
    maxRetries?: number;
    method: string;
    retryWaitMax?: number;
    retryWaitMin?: number;
    rootCAs?: string[];
    serverName?: string;
    url: string;
}

export interface Response {
    body: string;
    header: outputs.Header;
    status: string;
    statusCode: number;
}

