// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Http.Inputs
{

    public sealed class RequestArgs : Pulumi.ResourceArgs
    {
        [Input("body")]
        public Input<string>? Body { get; set; }

        [Input("certificates")]
        private InputList<string>? _certificates;
        public InputList<string> Certificates
        {
            get => _certificates ?? (_certificates = new InputList<string>());
            set => _certificates = value;
        }

        [Input("expectedStatusCode")]
        public Input<double>? ExpectedStatusCode { get; set; }

        [Input("header")]
        public Input<Inputs.HeaderArgs>? Header { get; set; }

        [Input("insecureSkipVerify")]
        public Input<bool>? InsecureSkipVerify { get; set; }

        [Input("maxRetries")]
        public Input<double>? MaxRetries { get; set; }

        [Input("method", required: true)]
        public Input<string> Method { get; set; } = null!;

        [Input("retryWaitMax")]
        public Input<double>? RetryWaitMax { get; set; }

        [Input("retryWaitMin")]
        public Input<double>? RetryWaitMin { get; set; }

        [Input("rootCAs")]
        private InputList<string>? _rootCAs;
        public InputList<string> RootCAs
        {
            get => _rootCAs ?? (_rootCAs = new InputList<string>());
            set => _rootCAs = value;
        }

        [Input("serverName")]
        public Input<string>? ServerName { get; set; }

        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public RequestArgs()
        {
        }
    }
}
